### ISSUE TITLE
Add the latest review date into the review

### ISSUE THREAD

**Issue by xcorail** [ossf/security-reviews#20]
I think it would help to add the review date in the main text, in addition to the metadata, so that a reader can identify immediately "old" reviews. (This issue will obviously have value only in a couple of years)

**Comment by scovetta** [comment]
I'd like to "publish" these reviews on a GitHub page (gh-pages) for easier consumption -- would featuring the date (or age of the review) be good if we just did it there, and didn't have it in two separate places within the raw review content?

**Comment by xcorail** [comment]
Yep! That would work. I will close this issue then.
