### ISSUE TITLE
Consider integrating with NPM Security Advisories

### ISSUE THREAD

**Issue by scovetta** [ossf/security-reviews#25]
The NPM Security Advisories database is available on GitHub (as structured data) at https://github.com/nodejs/security-advisories. We should consider whether periodically refreshing this content would be a good idea.

**Comment by dilanbhalla** [comment]
If you open this repo at https://github.com/dilanbhalla/security-advisories and click on the "reviews" folder you will see the 461 converted npm security reviews! There were 6 the script wasn't able to parse, so I'll take a look at those separately.

**Comment by scovetta** [comment]
At the 2/18 WG meeting we agreed to continue the conversation about this at our next WG meeting in early March.

**Comment by scovetta** [comment]
Closing, stale -- npm advisories are now rolled into GitHub advisories.
