### ISSUE TITLE
Review Requirements

### ISSUE THREAD

**Issue by dilanbhalla** [ossf/security-reviews#30]
I have a minor question about wording. In the quickstart page there is a checkbox stating "I agree that this review does not contain any significant, undisclosed, or unpatched security vulnerabilities," but why unpatched? If an old package has a critical vulnerability that is publicly known and was never fixed, shouldn't we be able to include that in the reviews?

**Comment by scovetta** [comment]
Good point -- If a vulnerability in an older version is being reported, it's by definition unpatched (in that older version). Some other scenarios:

1. Just found a serious issue: Not OK to submit, report to maintainer instead.
2. Found a serious issue, a fix was released: OK
3. Found a serious issue, reported to author, no response/action after... 90? days: OK
4. Found a non-serious / "insignificant" issue: OK

I think #3 is the problematic one -- when is it appropriate to disclose despite no patch being available? We should discuss with the WG on what kind of policy makes sense here.

**Comment by dilanbhalla** [comment]
This makes sense. Happy to discuss with the WG to get a better understanding of what boundaries we are working with, especially for #3 like you mentioned (and for #4 too, just to be sure what level/severity is acceptable to release!).

**Comment by dilanbhalla** [comment]
Think we resolved this in the most recent meeting, closing for now 👍
