### ISSUE TITLE
Publication-State: [ "Draft" | "Active" | "Removed" ]

### ISSUE THREAD

**Issue by dcmiddle** [ossf/security-reviews#35]
When would we commit a draft publication?
When would we not remove a review and instead leave it in the repo marked as removed?

**Comment by scovetta** [comment]
I'm not sure -- I was trying to build in a flexibility for the future. I suppose downstream consumers could filter out anything in draft/removed. We could, in the validator, only accept reviews with a publication status of 'active'.

**Comment by scovetta** [comment]
Completed via #42.
