### ISSUE TITLE
Publish quickstart via GitHub Pages

### ISSUE THREAD

**Issue by scovetta** [ossf/security-reviews#37]
The quickstart.html file should be accessible "live" rather than requiring a download/clone. I think this should be easy with GitHub Pages, but I haven't done that before, so if anyone would like to take this one, should be straightforward.

**Comment by luigigubello** [comment]
I have a website on Github Pages, maybe I can help you :) any requirements?

**Comment by scovetta** [comment]
Initially, it would be great if we could publish the quickstart.html page so we can switch links there and folks and just fill out the form "online" -- even though it's a static HTML page with no backend. Today, they'd have to clone the repo and open the file locally, which is awkward. 

I think we'll want to expand this over time, potentially publishing the actual reviews via Jekyll or something like that, but for now, just having a quickstart.html page that can open in the browser would be perfect.

**Comment by scovetta** [comment]
Completed, now available at https://ossf.github.io/security-reviews.
